name: Docker Image Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # this writes the tag name into GIT_TAG_NAME
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag markusressel/keel-telegram-bot:$GIT_TAG_NAME
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push the Docker image
        run: docker push markusressel/keel-telegram-bot:$GIT_TAG_NAME

  ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/markusressel/keel-telegram-bot
          tags: ${{ GIT_TAG_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: RELEASE_BRANCH=${{ steps.prep.outputs.branch }}
